(package "flymake-cursor"
         "1.0.2"
         "Show flymake messages in the minibuffer after delay")

(website-url "https://github.com/flymake/emacs-flymake-cursor")
(keywords "languages" "mode" "flymake")

(package-file "flymake-cursor.el")

(source "gnu")
(source "melpa")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
